# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -v
    ldflags:
      - -s -w
      - -X 'github.com/snowdreamtech/gserver/pkg/env.ProjectName=gserver'
      - -X 'github.com/snowdreamtech/gserver/pkg/env.Author=Snowdream Tech <snowdreamtech@qq.com>'
      - -X 'github.com/snowdreamtech/gserver/pkg/env.BuildTime=$(date -u +'%Y.%m.%d %H:%M:%S %z')'
      - -X 'github.com/snowdreamtech/gserver/pkg/env.CommitHash=$(git log -1 --pretty=format:%h 2>/dev/null || echo 'N/A')'
      - -X 'github.com/snowdreamtech/gserver/pkg/env.CommitHashFull=$(git log -1 --pretty=format:%H 2>/dev/null || echo 'N/A')'
      - -X 'github.com/snowdreamtech/gserver/pkg/env.GoVersion=$(go version | awk '{print $3,$4}')'
      - -X 'github.com/snowdreamtech/gserver/pkg/env.GitTag=$(git describe --tags --abbrev=0 2>/dev/null|| echo 'N/A')'
      - -X 'github.com/snowdreamtech/gserver/pkg/env.COPYRIGHT=Copyright (c) 2023-present SnowdreamTech Inc.'
      - -X 'github.com/snowdreamtech/gserver/pkg/env.LICENSE=MIT <https://github.com/snowdreamtech/gserver/blob/main/LICENSE>'
    goos:
      # - aix
      # - android
      - darwin
      # - dragonfly
      - freebsd
      # - illumos
      # - ios
      # - js
      - linux
      - netbsd
      - openbsd
      # - plan9
      - solaris
      # - wasip1
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - loong64
      - mips
      - mips64
      - mips64le
      - mipsle
      - ppc64
      - ppc64le
      - riscv64
      - s390x
      # - wasm
    # goamd64:
    #   - v2
    #   - v3
    goarm:
      - 5
      - 6
      - 7
    # goarm64:
    #   - v8.0
    # gomips:
    #   - hardfloat
    #   - softfloat
    # go386:
    #   - sse2
    #   - softfloat
    # goppc64:
    #   - power8
    #   - power9
    # goriscv64:
    #   - rva22u64
    ignore:
      - goos: plan9
        goarch: 386
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "^ci"
      - "^build"
      - "^style"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "New Refactorings"
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 150
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Dependency Updates"
      regexp: "^.*(feat|fix)\\(deps\\)*:+.*$"
      order: 300
    - title: "Documentation Updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999
